spring.profiles.active=local
spring.application.name=portfolio-document-service
management.endpoints.web.exposure.include=*
app.check.access.all=true
spring.cloud.circuitbreaker.resilience4j.enabled=true
spring.cloud.compatibility-verifier.enabled=false

feign.okhttp.enabled=true
feign.hystrix.enabled=true

com.sun.jndi.rmi.object.trustRLCodebase=false
com.sun.jndi.ldap.object.trustURLCodebase=false

spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB